DefaultContentLanguage = "en"
author = ""
baseURL = "https://fnxlabs.net"
copyright = ""
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
ignoreErrors = ["error-remote-getjson"]
languageCode = "en"
paginate = 3
theme = "github.com/jonathanjanssens/hugo-casper3"
title = "FNX Labs"
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10
[[menu.main]]
identifier = "image-credit"
name = "Image Credit"
url = "/image-credit/"
weight = 20
[[menu.main]]
identifier = "github-repo-theme"
name = "Get Theme on Github"
url = "https://github.com/jonathanjanssens/hugo-casper3"
weight = 30
[[menu.main]]
identifier = "author"
name = "Author Homepage"
url = "https://jonathanjanssens.com"
weight = 40
[params]
description = "FNX Labs"
facebook = ""
github = "https://github.com/FNX-Labs"
logo = "/images/fnxlogo-text-white.png"
mainSections = ["post"]
twitter = "https://twitter.com/fnxlabs"
[privacy.instagram]
disabled = false
simple = true
[privacy.twitter]
disabled = false
enableDNT = true
simple = true
[privacy.vimeo]
disabled = false
simple = true
[privacy.youtube]
disabled = false
privacyEnhanced = true
[services.instagram]
disableInlineCSS = true
[services.twitter]
disableInlineCSS = true
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
